package com.matijasokol.repo.detail.test

const val TAG_REPO_DETAIL_SCREEN = "TAG_REPO_DETAIL_SCREEN"
const val TAG_REPO_DETAIL_INFO_TEXT = "TAG_REPO_DETAIL_INFO_TEXT"
const val TAG_REPO_DETAIL_PROGRESS = "TAG_REPO_DETAIL_PROGRESS"
const val TAG_REPO_DETAIL_ERROR_TEXT = "TAG_REPO_DETAIL_ERROR_TEXT"
const val TAG_REPO_DETAIL_BUTTON_REPO_WEB = "TAG_REPO_DETAIL_BUTTON_REPO_WEB"
const val TAG_REPO_DETAIL_FOLLOWERS_COUNT = "TAG_REPO_DETAIL_FOLLOWERS_COUNT"
const val TAG_REPO_DETAIL_REPOS_COUNT = "TAG_REPO_DETAIL_REPOS_COUNT"
