package com.matijasokol.repo.list.test

const val TAG_REPO_SEARCH_BAR = "TAG_REPO_SEARCH_BAR"
const val TAG_REPO_LIST_ITEM = "TAG_REPO_LIST_ITEM"
const val TAG_REPO_INFO_MESSAGE = "TAG_REPO_INFO_MESSAGE"
const val TAG_REPO_NAME = "TAG_REPO_NAME"
const val TAG_PULL_TO_REFRESH = "TAG_PULL_TO_REFRESH"
