name: Distribute release free prod APK as artifact

on:
  workflow_dispatch:

jobs:
  distribute_release_build:
    runs-on: macos-latest
    env:
      GITHUBAPP_STORE_PASSWORD: '${{ secrets.GITHUBAPP_STORE_PASSWORD }}'
      GITHUBAPP_KEY_PASSWORD: '${{ secrets.GITHUBAPP_KEY_PASSWORD }}'

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Assemble
        run: |
          ./gradlew assembleProdFreeRelease --stacktrace

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-prod-free-release.apk
          path: app/build/outputs/apk/prodFree/release/